openapi: 3.0.0
info:
  title: marketplace
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /users:
    post:
      summary: Create New User
      operationId: post-users
      responses:
        '201':
          description: User Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                New User Bob Fellow:
                  value:
                    id: 12
                    firstName: Bob
                    lastName: Fellow
                    email: bob.fellow@gmail.com
                    dateOfBirth: '1996-08-24'
                    emailVerified: false
                    createDate: '2020-11-18'
        '400':
          description: Missing Required Information
        '409':
          description: Email Already Taken
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
            examples: {}
        description: Post the necessary fields for the API to create a new user.
      description: Creates a new user to the system.
    parameters: []
  /api/users:
    parameters: []
    post:
      summary: ''
      operationId: register-user
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Posting'
        '400':
          description: 'Bad Request, missing information'
      description: Registers new user into Marketplace.
  '/users/{userId}/posts/{postId}':
    parameters:
      - schema:
          type: string
        name: userId
        in: path
        required: true
      - schema:
          type: string
        name: postId
        in: path
        required: true
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Posting'
        '404':
          description: Not Found
      operationId: get-users-userId-postings-postingId
      description: ''
  '/posts/{postId}':
    parameters:
      - schema:
          type: string
        name: postId
        in: path
        required: true
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'
        '404':
          description: Not Found
          headers: {}
        '500':
          description: Internal Server Error
      operationId: get-postings-postingId
      description: Fetches the posting with the given id.
    put:
      summary: ''
      operationId: put-postings-postingId
      responses:
        '200':
          description: 'OK, Post updated.'
      description: Updates the Posting data.
    delete:
      summary: ''
      operationId: delete-postings-postingId
      responses:
        '200':
          description: 'OK, Post deleted.'
      description: Deletes the posting.
  '/users/{userId}':
    parameters:
      - schema:
          type: string
        name: userId
        in: path
        required: true
    delete:
      summary: Delete a specific user
      operationId: delete-users-userId
      responses:
        '202':
          description: Accepted
        '401':
          description: Unauthorized
        '404':
          description: User with id not found.
      security:
        - HTTPBasic: []
      description: Deleting the specific user.
    get:
      summary: Get information on a specific user
      operationId: get-users-userId
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
      security:
        - HTTPBasic: []
      description: Get data of specific user.
components:
  schemas:
    User:
      title: User
      type: object
      description: 'User of the marketplace, in this case the seller (or buyer) of products posted.'
      x-examples:
        example-1:
          id: '321'
          firstName: Konsta
          lastName: Holm
          email: user@example.com
          birthDate: '1999-03-19'
          creationDate: '2019-08-24'
          username: konstaholm
          address:
            street: Tietolinja 7
            country: Finland
            city: Oulu
            postalCode: 90570
          phoneNumber: '0441234123'
          password: pa$$word
      properties:
        id:
          description: Unique identifier of the user.
          type: string
        firstName:
          type: string
          description: First name of the user.
        lastName:
          type: string
          description: Last name of the user.
        email:
          type: string
          format: email
          description: Email of the user.
        birthDate:
          type: string
          format: date
          example: '1997-10-31'
          description: Birthdate of the user.
        creationDate:
          type: string
          format: date
          description: The date user was created.
        username:
          type: string
          description: Username of the user.
        address:
          type: object
          description: Address of the user.
          properties:
            street:
              type: string
            country:
              type: string
            city:
              type: string
            postalCode:
              type: number
          required:
            - country
        phoneNumber:
          type: string
          description: Phone number of the user.
        password:
          type: string
          description: Password of the user.
          format: password
      required:
        - firstName
        - lastName
        - email
        - birthDate
        - username
        - phoneNumber
        - password
    Post:
      title: Posting
      type: object
      description: Posting describes an item to be sold in the marketplace
      properties:
        id:
          type: string
          description: Identification number of the posting
        description:
          type: string
          description: Description of the posting
        title:
          type: string
          description: Title of the posting
        category:
          type: string
          enum:
            - Computers
            - Vehicles
            - Clothes
            - Jobs
          description: Category of the item being sold
        askingPrice:
          type: number
          description: Price of the product
        createdAt:
          type: string
          format: date-time
          description: Date of the ad created
        deliveryType:
          type: string
          enum:
            - Shipping
            - Pickup
          description: Delivery type of sold product
        seller:
          $ref: '#/components/schemas/User'
        location:
          $ref: '#/components/schemas/Location'
        images:
          type: string
          description: Images of the product being sold.
      required:
        - title
        - category
        - askingPrice
        - seller
        - location
      x-examples:
        example-1:
          id: string
          description: string
          title: string
          category: Computers
          askingPrice: 0
          createdAt: '2019-08-24T14:15:22Z'
          deliveryType: Shipping
          seller:
            id: string
            firstName: string
            lastName: string
            email: user@example.com
            birthDate: '1997-10-31'
            creationDate: '2019-08-24'
            username: string
            address:
              street: string
              country: string
              city: string
              postalCode: 0
            phoneNumber: string
            password: pa$$word
          location:
            city: string
            country: string
            id: string
          images: string
    Location:
      title: Location
      type: object
      properties:
        city:
          type: string
        country:
          type: string
        id:
          type: string
      required:
        - city
        - country
      x-examples:
        example-1:
          city: Oulu
          country: Finland
          id: string
    CreatedUser:
      title: CreatedUser
      type: object
      properties:
        id:
          type: string
      required:
        - id
  parameters:
    categories:
      name: categories
      in: query
      required: false
      schema:
        type: string
        format: uuid
      description: Returns postings based on the given category filter.
    posted:
      name: posted
      in: query
      required: false
      schema:
        type: string
    location:
      name: locaion
      in: query
      required: false
      schema:
        type: string
  responses:
    GET-Posts:
      description: Example response
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/Post'
          examples:
            example-1:
              value:
                - id: string
                  description: string
                  title: string
                  category: Computers
                  askingPrice: 0
                  createdAt: '2019-08-24T14:15:22Z'
                  deliveryType: Shipping
                  seller:
                    id: string
                    firstName: string
                    lastName: string
                    email: user@example.com
                    birthDate: '1997-10-31'
                    creationDate: '2019-08-24'
                    username: string
                    address:
                      street: string
                      country: string
                      city: string
                      postalCode: 0
                    phoneNumber: string
                    password: pa$$word
                  location:
                    city: string
                    country: string
                    id: string
                  images: string
        application/xml:
          schema:
            type: object
            properties: {}
        multipart/form-data:
          schema:
            type: object
            properties: {}
  securitySchemes:
    HTTPBasic:
      type: http
      scheme: basic
      description: ''
