openapi: 3.0.0
info:
  title: marketplace
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /api/users:
    parameters: []
    post:
      summary: ''
      operationId: register-user
      responses:
        '200':
          description: User was successfully created.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Bad Request
        '409':
          description: Username is already in use.
          content:
            application/json:
              schema:
                type: object
                properties: {}
        '500':
          description: Internal server error.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
      description: Registers a new user.
  '/api/posts/{id}':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
        description: The id of the displayed post.
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: Post was found and fetched.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Posting'
        '400':
          description: The given post id was in invalid format.
        '404':
          description: Post was not found.
      operationId: display-post
      description: Displays a post with the given id.
    put:
      summary: ''
      operationId: modify-post
      responses:
        '204':
          description: Post was found and modified.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'
              examples: {}
        '400':
          description: The given post id was in invalid format or some data was missing.
        '404':
          description: Post was not found.
        '500':
          description: Something bad happened.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error message describing the issue.
      description: Modifies a post with the given id.
      security:
        - JSONWebToken: []
    delete:
      summary: ''
      operationId: delete-post
      responses:
        '204':
          description: Post was found and deleted.
        '400':
          description: The given post id was in invalid format.
        '404':
          description: Post was not found.
      security:
        - JSONWebToken: []
      description: Deletes a post with the given id.
  /api/login:
    post:
      summary: ''
      operationId: login-user
      responses:
        '200':
          description: User was successfully logged in.
      description: Authenticates the user to use some Marketplace functionalities.
  /api/posts:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                description: Array of fetched and paged posts.
                items:
                  $ref: '#/components/schemas/Post'
      operationId: get-posts
      description: Displays paged posts.
      parameters:
        - schema:
            type: number
            example: 5
            minimum: 1
            default: 1
          in: query
          name: index
          description: The start index of posts returned.
        - schema:
            type: number
            minimum: 1
            maximum: 100
            example: 50
            default: 100
          in: query
          name: count
          description: The number of posts returned.
    parameters: []
    post:
      summary: ''
      operationId: create-post
      responses:
        '201':
          description: New post was created.
        '400':
          description: Invalid data.
      description: Creates a new post.
      security:
        - JSONWebToken: []
  /api/posts/search:
    post:
      summary: ''
      operationId: search-posts
      responses:
        '200':
          description: OK
        '500':
          description: Internal Server Error
        '':
          description: ''
      description: Performs a search query for posts based on given parameters.
      parameters:
        - schema:
            type: string
          in: query
          name: country
          description: The country of searched posts.
        - schema:
            type: string
          in: query
          name: city
          description: The city of searched posts.
        - schema:
            type: string
            format: date
          in: query
          name: posted
          description: The date of searched posts.
        - schema:
            type: string
          in: query
          name: category
          description: The category of searched posts.
    parameters: []
components:
  schemas:
    User:
      title: User
      type: object
      description: 'User of the marketplace, in this case the seller (or buyer) of products posted.'
      x-examples:
        example-1:
          id: '321'
          firstName: Konsta
          lastName: Holm
          email: user@example.com
          birthDate: '1999-03-19'
          creationDate: '2019-08-24'
          username: konstaholm
          address:
            street: Tietolinja 7
            country: Finland
            city: Oulu
            postalCode: 90570
          phoneNumber: '0441234123'
          password: pa$$word
      properties:
        id:
          description: Unique identifier of the user.
          type: string
        firstName:
          type: string
          description: First name of the user.
        lastName:
          type: string
          description: Last name of the user.
        email:
          type: string
          format: email
          description: Email of the user.
        birthDate:
          type: string
          format: date
          example: '1997-10-31'
          description: Birthdate of the user.
        creationDate:
          type: string
          format: date
          description: The date user was created.
        username:
          type: string
          description: Username of the user.
        address:
          type: object
          description: Address of the user.
          properties:
            street:
              type: string
            country:
              type: string
            city:
              type: string
            postalCode:
              type: number
          required:
            - country
        phoneNumber:
          type: string
          description: Phone number of the user.
        password:
          type: string
          description: Password of the user.
          format: password
      required:
        - firstName
        - lastName
        - email
        - birthDate
        - username
        - phoneNumber
        - password
    Post:
      title: Posting
      type: object
      description: Posting describes an item to be sold in the marketplace
      properties:
        id:
          type: string
          description: Identification number of the posting
        description:
          type: string
          description: Description of the posting
        title:
          type: string
          description: Title of the posting
        category:
          type: string
          enum:
            - Computers
            - Vehicles
            - Clothes
            - Jobs
          description: Category of the item being sold
        askingPrice:
          type: number
          description: Price of the product
        createdAt:
          type: string
          format: date-time
          description: Date of the ad created
        deliveryType:
          type: string
          enum:
            - Shipping
            - Pickup
          description: Delivery type of sold product
        seller:
          $ref: '#/components/schemas/User'
        location:
          $ref: '#/components/schemas/Location'
        images:
          type: string
          description: Images of the product being sold.
      required:
        - title
        - category
        - askingPrice
        - seller
        - location
      x-examples:
        example-1:
          id: string
          description: string
          title: string
          category: Computers
          askingPrice: 0
          createdAt: '2019-08-24T14:15:22Z'
          deliveryType: Shipping
          seller:
            id: string
            firstName: string
            lastName: string
            email: user@example.com
            birthDate: '1997-10-31'
            creationDate: '2019-08-24'
            username: string
            address:
              street: string
              country: string
              city: string
              postalCode: 0
            phoneNumber: string
            password: pa$$word
          location:
            city: string
            country: string
            id: string
          images: string
    Location:
      title: Location
      type: object
      properties:
        city:
          type: string
        country:
          type: string
        id:
          type: string
      required:
        - city
        - country
      x-examples:
        example-1:
          city: Oulu
          country: Finland
          id: string
    CreatedUser:
      title: CreatedUser
      type: object
      properties:
        id:
          type: string
      required:
        - id
  parameters: {}
  responses:
    GET-Posts:
      description: Example response
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/Post'
          examples:
            example-1:
              value:
                - id: string
                  description: string
                  title: string
                  category: Computers
                  askingPrice: 0
                  createdAt: '2019-08-24T14:15:22Z'
                  deliveryType: Shipping
                  seller:
                    id: string
                    firstName: string
                    lastName: string
                    email: user@example.com
                    birthDate: '1997-10-31'
                    creationDate: '2019-08-24'
                    username: string
                    address:
                      street: string
                      country: string
                      city: string
                      postalCode: 0
                    phoneNumber: string
                    password: pa$$word
                  location:
                    city: string
                    country: string
                    id: string
                  images: string
        application/xml:
          schema:
            type: object
            properties: {}
        multipart/form-data:
          schema:
            type: object
            properties: {}
    Bad-Request:
      description: Example response
      content:
        application/json:
          schema:
            type: object
  securitySchemes:
    JSONWebToken:
      type: http
      scheme: bearer
      description: ''
